# Application Settings
app:
  env: ${APP_ENV:dev}
  base_url: ${BASE_URL:http://localhost:8000}

# Database Configuration
db:
  url: ${DB_URL}

# Logging Configuration
logging:
  level: INFO

# Scheduler Settings
scheduling:
  osint_poll_minutes: 60

# API Rate Limits
rate_limits:
  osint:
    shodan: 60
    censys: 60
