"""init

Revision ID: 01b6e0e84fc6
Revises: 
Create Date: 2025-10-02 20:22:17.131516+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01b6e0e84fc6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('criticality', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_name'), 'assets', ['name'], unique=False)
    op.create_table('intel_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('indicator', sa.String(length=255), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intel_events_indicator'), 'intel_events', ['indicator'], unique=False)
    op.create_index(op.f('ix_intel_events_source'), 'intel_events', ['source'], unique=False)
    op.create_table('risk_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('likelihood', sa.Integer(), nullable=False),
    sa.Column('impact', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_items_asset_id'), 'risk_items', ['asset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_items_asset_id'), table_name='risk_items')
    op.drop_table('risk_items')
    op.drop_index(op.f('ix_intel_events_source'), table_name='intel_events')
    op.drop_index(op.f('ix_intel_events_indicator'), table_name='intel_events')
    op.drop_table('intel_events')
    op.drop_index(op.f('ix_assets_name'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
