"""Expand asset model and add linking table

Revision ID: 5e6191c9e0a0
Revises: a1b2c3d4e5f6
Create Date: 2025-10-15 01:20:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e6191c9e0a0'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

assettypeenum = sa.Enum('HW', 'SW', 'DATA', 'USER', 'SERVICE', name='assettypeenum')
datasensitivityenum = sa.Enum('LOW', 'MODERATE', 'HIGH', name='datasensitivityenum')
matchtypeenum = sa.Enum('IP', 'DOMAIN', 'HOSTNAME', name='matchtypeenum')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_intel_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('intel_event_id', sa.Integer(), nullable=True),
    sa.Column('match_type', matchtypeenum, nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['intel_event_id'], ['intel_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_intel_links_asset_id'), 'asset_intel_links', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_intel_links_intel_event_id'), 'asset_intel_links', ['intel_event_id'], unique=False)
    
    bind = op.get_bind()
    assettypeenum.create(bind)
    datasensitivityenum.create(bind)

    op.add_column('assets', sa.Column('ip', sa.String(length=45), nullable=True))
    op.add_column('assets', sa.Column('hostname', sa.String(length=255), nullable=True))
    op.add_column('assets', sa.Column('owner', sa.String(length=120), nullable=True))
    op.add_column('assets', sa.Column('business_unit', sa.String(length=120), nullable=True))
    op.add_column('assets', sa.Column('data_sensitivity', datasensitivityenum, nullable=True))
    op.create_index(op.f('ix_assets_hostname'), 'assets', ['hostname'], unique=False)
    op.create_index(op.f('ix_assets_ip'), 'assets', ['ip'], unique=False)
    op.alter_column('assets', 'type',
               existing_type=sa.VARCHAR(length=40),
               type_=assettypeenum,
               existing_nullable=True,
               postgresql_using='type::assettypeenum')
    op.alter_column('assets', 'name',
               existing_type=sa.VARCHAR(length=120),
               unique=True)

    op.execute("UPDATE assets SET data_sensitivity = 'LOW'")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'name',
               existing_type=sa.VARCHAR(length=120),
               unique=False)
    op.alter_column('assets', 'type',
               existing_type=assettypeenum,
               type_=sa.VARCHAR(length=40),
               existing_nullable=True,
               postgresql_using='type::text')
    op.drop_index(op.f('ix_assets_ip'), table_name='assets')
    op.drop_index(op.f('ix_assets_hostname'), table_name='assets')
    op.drop_column('assets', 'data_sensitivity')
    op.drop_column('assets', 'business_unit')
    op.drop_column('assets', 'owner')
    op.drop_column('assets', 'hostname')
    op.drop_column('assets', 'ip')
    op.drop_index(op.f('ix_asset_intel_links_intel_event_id'), table_name='asset_intel_links')
    op.drop_index(op.f('ix_asset_intel_links_asset_id'), table_name='asset_intel_links')
    op.drop_table('asset_intel_links')

    assettypeenum.drop(op.get_bind())
    datasensitivityenum.drop(op.get_bind())
    matchtypeenum.drop(op.get_bind())
    # ### end Alembic commands ###
