name: CI

on: [push, pull_request]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install backend dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r src/backend/requirements.txt
          pip install ruff pytest
      - name: Lint with ruff
        run: |
          source .venv/bin/activate
          ruff check src/backend

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install frontend dependencies
        run: npm install --prefix src/frontend
      - name: Lint with ESLint
        run: npm run lint --prefix src/frontend
      # Add tests here when they exist
      # - name: Test with Vitest
      #   run: npm run test --prefix src/frontend

  secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITLEAKS_LICENSE }}
